version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dynamic_form
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend/server
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: dynamic_form
      JWT_SECRET: your-secret-key
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: .
    depends_on:
      - backend
    ports:
      - "8081:8081"
    environment:
      # Thêm biến môi trường nếu frontend cần biết API_URL
      API_URL: http://localhost:3000

volumes:
  pgdata:
